[package]
name = "edtest"
version = "0.1.0"
edition = "2024"

[dependencies]
edtest_macros = { path = "../edtest_macros" }

rstest = { workspace = true }
test-log = { workspace = true, features = ["trace"] }
serial_test = { workspace = true }
static_assertions = { workspace = true }
